let str1="hello";
let str2=" Ritesh";
let str3=str1+str2;
console.log(str3);
console.log("1"+2+2);
console.log(1+"2"+2);
console.log(1+2+"2");
console.log(+true);
console.log(2+2);
console.log(2-2);
console.log(2*2);
console.log(2**3);
console.log(2/2);
console.log(2%2);
// console.log(2++);
// console.log(++2);
console.log(+null);
